[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = '../common' }
db = { path = '../db' }
types = { path = '../types' }
dotenv = "0.15.0"
axum = "0.8.9"
tokio = { version = "1.52.3", features = ["rt-multi-thread"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sqlx = { version = "0.9", features = ["runtime-tokio", "any", "postgres", "tls-rustls"] }
tower = "0.5.3"
tower-http = { version = "0.6.11", features = ["cors"] }
serde = { version = "1.0.228", features = ["derive"] }
validator = { version = "0.20.0", features = ["derive"] }
serde_json = "1.0.150"
argon2 = "0.5.3"
rand_core = { version = "0.6.4", features = ["getrandom"] }
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }
uuid = { version = "1.23.5", features = ["v4"] }
base64 = "0.22.1"
sha2 = "0.10.9"
hex = "0.4.3"

